name: deploy-ishowtv

on:
  push:
    branches:
      - master

env:
  BRANCH_NAME: ${{ github.ref }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Display Branch Name
        run: echo "Current Branch: ${{ github.ref }}"

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Netlify
        run: echo "Current Branch: ${{ github.ref }}" 
        run: |
          prod_flag=""
          if [ "$BRANCH_NAME" == "master" ]; then prod_flag="--prod"; fi
          netlify deploy \
            --dir build \
            --site  ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
            $prod_flag
